# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Compute_E_step <- function(index, first_order, second_order) {
    .Call('_NNRPanel_Compute_E_step', PACKAGE = 'NNRPanel', index, first_order, second_order)
}

Compute_M_step <- function(Mu, X, L, R, num_factor) {
    .Call('_NNRPanel_Compute_M_step', PACKAGE = 'NNRPanel', Mu, X, L, R, num_factor)
}

EM_logit <- function(Y, X, beta_0, L_0, R_0, num_factor, iter_max, tol) {
    .Call('_NNRPanel_EM_logit', PACKAGE = 'NNRPanel', Y, X, beta_0, L_0, R_0, num_factor, iter_max, tol)
}

SVD <- function(A) {
    .Call('_NNRPanel_SVD', PACKAGE = 'NNRPanel', A)
}

SVT <- function(U, V, sigma, lambda) {
    .Call('_NNRPanel_SVT', PACKAGE = 'NNRPanel', U, V, sigma, lambda)
}

Low_rank_appro <- function(Theta, num_factor) {
    .Call('_NNRPanel_Low_rank_appro', PACKAGE = 'NNRPanel', Theta, num_factor)
}

Compute_generalized_inverse <- function(A) {
    .Call('_NNRPanel_Compute_generalized_inverse', PACKAGE = 'NNRPanel', A)
}

Compute_index_with_theta <- function(X, beta, Theta) {
    .Call('_NNRPanel_Compute_index_with_theta', PACKAGE = 'NNRPanel', X, beta, Theta)
}

Compute_index_with_theta_FE <- function(X, beta, fe_N, fe_T, Theta) {
    .Call('_NNRPanel_Compute_index_with_theta_FE', PACKAGE = 'NNRPanel', X, beta, fe_N, fe_T, Theta)
}

Compute_index_with_LR <- function(X, beta, L, R) {
    .Call('_NNRPanel_Compute_index_with_LR', PACKAGE = 'NNRPanel', X, beta, L, R)
}

Compute_index_with_LR_FE <- function(X, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_index_with_LR_FE', PACKAGE = 'NNRPanel', X, beta, fe_N, fe_T, L, R)
}

Convert_numeric_matrix_to_vector <- function(A) {
    .Call('_NNRPanel_Convert_numeric_matrix_to_vector', PACKAGE = 'NNRPanel', A)
}

Convert_integer_matrix_to_vector <- function(A) {
    .Call('_NNRPanel_Convert_integer_matrix_to_vector', PACKAGE = 'NNRPanel', A)
}

Convert_List_to_vector <- function(X) {
    .Call('_NNRPanel_Convert_List_to_vector', PACKAGE = 'NNRPanel', X)
}

Convert_FE_to_regressor <- function(L, R) {
    .Call('_NNRPanel_Convert_FE_to_regressor', PACKAGE = 'NNRPanel', L, R)
}

Compute_weighted <- function(X, Lambda, Gamma, W) {
    .Call('_NNRPanel_Compute_weighted', PACKAGE = 'NNRPanel', X, Lambda, Gamma, W)
}

Compute_weighted_FE <- function(X, Lambda, Gamma, W) {
    .Call('_NNRPanel_Compute_weighted_FE', PACKAGE = 'NNRPanel', X, Lambda, Gamma, W)
}

Create_X_res <- function(X, Lambda, Gamma, W) {
    .Call('_NNRPanel_Create_X_res', PACKAGE = 'NNRPanel', X, Lambda, Gamma, W)
}

Compute_bias_corr_W <- function(second_order, X_res_) {
    .Call('_NNRPanel_Compute_bias_corr_W', PACKAGE = 'NNRPanel', second_order, X_res_)
}

Compute_bias_corr_V <- function(first_order, X_res_) {
    .Call('_NNRPanel_Compute_bias_corr_V', PACKAGE = 'NNRPanel', first_order, X_res_)
}

Compute_bias_corr_D <- function(first_order, second_order, third_order, Lambda, X_res_) {
    .Call('_NNRPanel_Compute_bias_corr_D', PACKAGE = 'NNRPanel', first_order, second_order, third_order, Lambda, X_res_)
}

Compute_bias_corr_D_probit <- function(beta, first_order, second_order, Lambda, X_res_) {
    .Call('_NNRPanel_Compute_bias_corr_D_probit', PACKAGE = 'NNRPanel', beta, first_order, second_order, Lambda, X_res_)
}

Compute_bias_corr_B <- function(first_order, second_order, third_order, Gamma, X_res_, truc) {
    .Call('_NNRPanel_Compute_bias_corr_B', PACKAGE = 'NNRPanel', first_order, second_order, third_order, Gamma, X_res_, truc)
}

Compute_bias_corr_B_probit <- function(beta, first_order, second_order, Gamma, X_res_, truc) {
    .Call('_NNRPanel_Compute_bias_corr_B_probit', PACKAGE = 'NNRPanel', beta, first_order, second_order, Gamma, X_res_, truc)
}

Compute_bias_corr_logit <- function(Y, X, beta, L, R, truc) {
    .Call('_NNRPanel_Compute_bias_corr_logit', PACKAGE = 'NNRPanel', Y, X, beta, L, R, truc)
}

Compute_bias_corr_logit_robust <- function(Y, X, beta, L, R, truc) {
    .Call('_NNRPanel_Compute_bias_corr_logit_robust', PACKAGE = 'NNRPanel', Y, X, beta, L, R, truc)
}

Compute_bias_corr_poisson <- function(Y, X, beta, L, R, truc) {
    .Call('_NNRPanel_Compute_bias_corr_poisson', PACKAGE = 'NNRPanel', Y, X, beta, L, R, truc)
}

Compute_bias_corr_poisson_robust <- function(Y, X, beta, L, R, truc) {
    .Call('_NNRPanel_Compute_bias_corr_poisson_robust', PACKAGE = 'NNRPanel', Y, X, beta, L, R, truc)
}

Compute_bias_corr_probit <- function(Y, X, beta, L, R, truc) {
    .Call('_NNRPanel_Compute_bias_corr_probit', PACKAGE = 'NNRPanel', Y, X, beta, L, R, truc)
}

Compute_bias_corr_probit_robust <- function(Y, X, beta, L, R, truc) {
    .Call('_NNRPanel_Compute_bias_corr_probit_robust', PACKAGE = 'NNRPanel', Y, X, beta, L, R, truc)
}

Compute_bias_corr_linear <- function(Y, X, beta, L, R, truc) {
    .Call('_NNRPanel_Compute_bias_corr_linear', PACKAGE = 'NNRPanel', Y, X, beta, L, R, truc)
}

Compute_bias_corr_linear_robust <- function(Y, X, beta, L, R, truc) {
    .Call('_NNRPanel_Compute_bias_corr_linear_robust', PACKAGE = 'NNRPanel', Y, X, beta, L, R, truc)
}

Update_beta <- function(beta, score_beta, s) {
    .Call('_NNRPanel_Update_beta', PACKAGE = 'NNRPanel', beta, score_beta, s)
}

Update_theta <- function(Theta, score_theta, s, phi) {
    .Call('_NNRPanel_Update_theta', PACKAGE = 'NNRPanel', Theta, score_theta, s, phi)
}

Update_LR <- function(L, R, score_L, score_R, s_L, s_R) {
    .Call('_NNRPanel_Update_LR', PACKAGE = 'NNRPanel', L, R, score_L, score_R, s_L, s_R)
}

Update_FE <- function(fe_N, fe_T, score_fe_N, score_fe_T, s_N, s_T) {
    .Call('_NNRPanel_Update_FE', PACKAGE = 'NNRPanel', fe_N, fe_T, score_fe_N, score_fe_T, s_N, s_T)
}

fit_logit <- function(X, Y, phi, s, iter_max, tol) {
    .Call('_NNRPanel_fit_logit', PACKAGE = 'NNRPanel', X, Y, phi, s, iter_max, tol)
}

MLE_logit <- function(X, Y, beta_0, L_0, R_0, s, iter_max, tol) {
    .Call('_NNRPanel_MLE_logit', PACKAGE = 'NNRPanel', X, Y, beta_0, L_0, R_0, s, iter_max, tol)
}

fit_poisson <- function(X, Y, phi, s, iter_max, tol, beta_init = numeric(0)) {
    .Call('_NNRPanel_fit_poisson', PACKAGE = 'NNRPanel', X, Y, phi, s, iter_max, tol, beta_init)
}

fit_poisson_FE <- function(X, Y, phi, s, iter_max, tol, beta_init = numeric(0)) {
    .Call('_NNRPanel_fit_poisson_FE', PACKAGE = 'NNRPanel', X, Y, phi, s, iter_max, tol, beta_init)
}

fit_poisson_FE_w <- function(X, Y, phi, s, iter_max, tol, fe_N_0, fe_T_0, beta_init = numeric(0)) {
    .Call('_NNRPanel_fit_poisson_FE_w', PACKAGE = 'NNRPanel', X, Y, phi, s, iter_max, tol, fe_N_0, fe_T_0, beta_init)
}

MLE_poisson <- function(X, Y, beta_0, L_0, R_0, s, iter_max, tol) {
    .Call('_NNRPanel_MLE_poisson', PACKAGE = 'NNRPanel', X, Y, beta_0, L_0, R_0, s, iter_max, tol)
}

MLE_poisson_FE <- function(X, Y, beta_0, fe_N_0, fe_T_0, L_0, R_0, s, iter_max, tol) {
    .Call('_NNRPanel_MLE_poisson_FE', PACKAGE = 'NNRPanel', X, Y, beta_0, fe_N_0, fe_T_0, L_0, R_0, s, iter_max, tol)
}

MLE_poisson_LR <- function(X, Y, beta_0, L_0, R_0, s, iter_max, tol) {
    .Call('_NNRPanel_MLE_poisson_LR', PACKAGE = 'NNRPanel', X, Y, beta_0, L_0, R_0, s, iter_max, tol)
}

fit_probit <- function(X, Y, phi, s, iter_max, tol) {
    .Call('_NNRPanel_fit_probit', PACKAGE = 'NNRPanel', X, Y, phi, s, iter_max, tol)
}

MLE_probit <- function(X, Y, beta_0, L_0, R_0, s, iter_max, tol) {
    .Call('_NNRPanel_MLE_probit', PACKAGE = 'NNRPanel', X, Y, beta_0, L_0, R_0, s, iter_max, tol)
}

fit_linear <- function(X, Y, phi, s, iter_max, tol) {
    .Call('_NNRPanel_fit_linear', PACKAGE = 'NNRPanel', X, Y, phi, s, iter_max, tol)
}

MLE_linear <- function(X, Y, beta_0, L_0, R_0, s, iter_max, tol) {
    .Call('_NNRPanel_MLE_linear', PACKAGE = 'NNRPanel', X, Y, beta_0, L_0, R_0, s, iter_max, tol)
}

Compute_logl_poisson_with_theta_FE_network <- function(X, Y, beta, fe_N, fe_T, Theta) {
    .Call('_NNRPanel_Compute_logl_poisson_with_theta_FE_network', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, Theta)
}

Compute_logl_poisson_with_LR_FE_network <- function(X, Y, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_logl_poisson_with_LR_FE_network', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, L, R)
}

Compute_score_poisson_with_theta_FE_network <- function(X, Y, beta, fe_N, fe_T, Theta) {
    .Call('_NNRPanel_Compute_score_poisson_with_theta_FE_network', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, Theta)
}

Compute_score_poisson_with_LR_FE_network <- function(X, Y, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_score_poisson_with_LR_FE_network', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, L, R)
}

Compute_obj_poisson_with_theta_FE_network <- function(X, Y, beta, fe_N, fe_T, Theta, sigma_sum, phi) {
    .Call('_NNRPanel_Compute_obj_poisson_with_theta_FE_network', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, Theta, sigma_sum, phi)
}

Compute_obj_poisson_with_LR_FE_network <- function(X, Y, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_obj_poisson_with_LR_FE_network', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, L, R)
}

Compute_first_order_poisson_with_LR_FE_network <- function(X, Y, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_first_order_poisson_with_LR_FE_network', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, L, R)
}

Compute_second_order_poisson_with_LR_FE_network <- function(X, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_second_order_poisson_with_LR_FE_network', PACKAGE = 'NNRPanel', X, beta, fe_N, fe_T, L, R)
}

Update_beta_network <- function(beta, score_beta, s) {
    .Call('_NNRPanel_Update_beta_network', PACKAGE = 'NNRPanel', beta, score_beta, s)
}

Update_theta_network <- function(Theta, score_theta, s, phi) {
    .Call('_NNRPanel_Update_theta_network', PACKAGE = 'NNRPanel', Theta, score_theta, s, phi)
}

Update_LR_network <- function(L, R, score_L, score_R, s_L, s_R) {
    .Call('_NNRPanel_Update_LR_network', PACKAGE = 'NNRPanel', L, R, score_L, score_R, s_L, s_R)
}

Update_FE_network <- function(fe_N, fe_T, score_fe_N, score_fe_T, s_N, s_T) {
    .Call('_NNRPanel_Update_FE_network', PACKAGE = 'NNRPanel', fe_N, fe_T, score_fe_N, score_fe_T, s_N, s_T)
}

fit_poisson_FE_network <- function(X, Y, phi, s, iter_max, tol, fe_N_0, fe_T_0, beta_init = numeric(0)) {
    .Call('_NNRPanel_fit_poisson_FE_network', PACKAGE = 'NNRPanel', X, Y, phi, s, iter_max, tol, fe_N_0, fe_T_0, beta_init)
}

MLE_poisson_FE_network <- function(X, Y, beta_0, fe_N_0, fe_T_0, L_0, R_0, s, iter_max, tol) {
    .Call('_NNRPanel_MLE_poisson_FE_network', PACKAGE = 'NNRPanel', X, Y, beta_0, fe_N_0, fe_T_0, L_0, R_0, s, iter_max, tol)
}

Compute_logl_linear_with_theta <- function(X, Y, beta, Theta) {
    .Call('_NNRPanel_Compute_logl_linear_with_theta', PACKAGE = 'NNRPanel', X, Y, beta, Theta)
}

Compute_logl_linear_with_theta_FE <- function(X, Y, beta, fe_N, fe_T, Theta) {
    .Call('_NNRPanel_Compute_logl_linear_with_theta_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, Theta)
}

Compute_logl_linear_with_LR <- function(X, Y, beta, L, R) {
    .Call('_NNRPanel_Compute_logl_linear_with_LR', PACKAGE = 'NNRPanel', X, Y, beta, L, R)
}

Compute_logl_linear_with_LR_FE <- function(X, Y, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_logl_linear_with_LR_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, L, R)
}

Compute_score_linear_with_theta <- function(X, Y, beta, Theta) {
    .Call('_NNRPanel_Compute_score_linear_with_theta', PACKAGE = 'NNRPanel', X, Y, beta, Theta)
}

Compute_score_linear_with_theta_FE <- function(X, Y, beta, fe_N, fe_T, Theta) {
    .Call('_NNRPanel_Compute_score_linear_with_theta_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, Theta)
}

Compute_score_linear_with_LR <- function(X, Y, beta, L, R) {
    .Call('_NNRPanel_Compute_score_linear_with_LR', PACKAGE = 'NNRPanel', X, Y, beta, L, R)
}

Compute_score_linear_with_LR_FE <- function(X, Y, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_score_linear_with_LR_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, L, R)
}

Compute_obj_linear_with_theta <- function(X, Y, beta, Theta, sigma_sum, phi) {
    .Call('_NNRPanel_Compute_obj_linear_with_theta', PACKAGE = 'NNRPanel', X, Y, beta, Theta, sigma_sum, phi)
}

Compute_obj_linear_with_theta_FE <- function(X, Y, beta, fe_N, fe_T, Theta, sigma_sum, phi) {
    .Call('_NNRPanel_Compute_obj_linear_with_theta_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, Theta, sigma_sum, phi)
}

Compute_obj_linear_with_LR <- function(X, Y, beta, L, R) {
    .Call('_NNRPanel_Compute_obj_linear_with_LR', PACKAGE = 'NNRPanel', X, Y, beta, L, R)
}

Compute_obj_linear_with_LR_FE <- function(X, Y, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_obj_linear_with_LR_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, L, R)
}

Compute_first_order_linear_with_LR <- function(X, Y, beta, L, R) {
    .Call('_NNRPanel_Compute_first_order_linear_with_LR', PACKAGE = 'NNRPanel', X, Y, beta, L, R)
}

Compute_logl_logit_with_theta <- function(X, Y, beta, Theta) {
    .Call('_NNRPanel_Compute_logl_logit_with_theta', PACKAGE = 'NNRPanel', X, Y, beta, Theta)
}

Compute_logl_logit_with_theta_FE <- function(X, Y, beta, fe_N, fe_T, Theta) {
    .Call('_NNRPanel_Compute_logl_logit_with_theta_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, Theta)
}

Compute_logl_logit_with_LR <- function(X, Y, beta, L, R) {
    .Call('_NNRPanel_Compute_logl_logit_with_LR', PACKAGE = 'NNRPanel', X, Y, beta, L, R)
}

Compute_logl_logit_with_LR_FE <- function(X, Y, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_logl_logit_with_LR_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, L, R)
}

Compute_score_logit_with_theta <- function(X, Y, beta, Theta) {
    .Call('_NNRPanel_Compute_score_logit_with_theta', PACKAGE = 'NNRPanel', X, Y, beta, Theta)
}

Compute_score_logit_with_theta_FE <- function(X, Y, beta, fe_N, fe_T, Theta) {
    .Call('_NNRPanel_Compute_score_logit_with_theta_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, Theta)
}

Compute_score_logit_with_LR <- function(X, Y, beta, L, R) {
    .Call('_NNRPanel_Compute_score_logit_with_LR', PACKAGE = 'NNRPanel', X, Y, beta, L, R)
}

Compute_score_logit_with_LR_FE <- function(X, Y, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_score_logit_with_LR_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, L, R)
}

Compute_obj_logit_with_theta <- function(X, Y, beta, Theta, sigma_sum, phi) {
    .Call('_NNRPanel_Compute_obj_logit_with_theta', PACKAGE = 'NNRPanel', X, Y, beta, Theta, sigma_sum, phi)
}

Compute_obj_logit_with_theta_FE <- function(X, Y, beta, fe_N, fe_T, Theta, sigma_sum, phi) {
    .Call('_NNRPanel_Compute_obj_logit_with_theta_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, Theta, sigma_sum, phi)
}

Compute_obj_logit_with_LR <- function(X, Y, beta, L, R) {
    .Call('_NNRPanel_Compute_obj_logit_with_LR', PACKAGE = 'NNRPanel', X, Y, beta, L, R)
}

Compute_obj_logit_with_LR_FE <- function(X, Y, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_obj_logit_with_LR_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, L, R)
}

Compute_first_order_logit_with_LR <- function(X, Y, beta, L, R) {
    .Call('_NNRPanel_Compute_first_order_logit_with_LR', PACKAGE = 'NNRPanel', X, Y, beta, L, R)
}

Compute_second_order_logit_with_LR <- function(X, beta, L, R) {
    .Call('_NNRPanel_Compute_second_order_logit_with_LR', PACKAGE = 'NNRPanel', X, beta, L, R)
}

Compute_third_order_logit_with_LR <- function(X, beta, L, R) {
    .Call('_NNRPanel_Compute_third_order_logit_with_LR', PACKAGE = 'NNRPanel', X, beta, L, R)
}

Sim_dynamic_logit <- function(Z, beta_W, beta_Z, Theta) {
    .Call('_NNRPanel_Sim_dynamic_logit', PACKAGE = 'NNRPanel', Z, beta_W, beta_Z, Theta)
}

Compute_logl_poisson_with_theta <- function(X, Y, beta, Theta) {
    .Call('_NNRPanel_Compute_logl_poisson_with_theta', PACKAGE = 'NNRPanel', X, Y, beta, Theta)
}

Compute_logl_poisson_with_theta_FE <- function(X, Y, beta, fe_N, fe_T, Theta) {
    .Call('_NNRPanel_Compute_logl_poisson_with_theta_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, Theta)
}

Compute_logl_poisson_with_LR <- function(X, Y, beta, L, R) {
    .Call('_NNRPanel_Compute_logl_poisson_with_LR', PACKAGE = 'NNRPanel', X, Y, beta, L, R)
}

Compute_logl_poisson_with_LR_FE <- function(X, Y, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_logl_poisson_with_LR_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, L, R)
}

Compute_score_poisson_with_theta <- function(X, Y, beta, Theta) {
    .Call('_NNRPanel_Compute_score_poisson_with_theta', PACKAGE = 'NNRPanel', X, Y, beta, Theta)
}

Compute_score_poisson_with_theta_FE <- function(X, Y, beta, fe_N, fe_T, Theta) {
    .Call('_NNRPanel_Compute_score_poisson_with_theta_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, Theta)
}

Compute_score_poisson_with_LR <- function(X, Y, beta, L, R) {
    .Call('_NNRPanel_Compute_score_poisson_with_LR', PACKAGE = 'NNRPanel', X, Y, beta, L, R)
}

Compute_score_poisson_with_LR_FE <- function(X, Y, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_score_poisson_with_LR_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, L, R)
}

Compute_obj_poisson_with_theta <- function(X, Y, beta, Theta, sigma_sum, phi) {
    .Call('_NNRPanel_Compute_obj_poisson_with_theta', PACKAGE = 'NNRPanel', X, Y, beta, Theta, sigma_sum, phi)
}

Compute_obj_poisson_with_theta_FE <- function(X, Y, beta, fe_N, fe_T, Theta, sigma_sum, phi) {
    .Call('_NNRPanel_Compute_obj_poisson_with_theta_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, Theta, sigma_sum, phi)
}

Compute_obj_poisson_with_LR <- function(X, Y, beta, L, R) {
    .Call('_NNRPanel_Compute_obj_poisson_with_LR', PACKAGE = 'NNRPanel', X, Y, beta, L, R)
}

Compute_obj_poisson_with_LR_FE <- function(X, Y, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_obj_poisson_with_LR_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, L, R)
}

Compute_first_order_poisson_with_LR <- function(X, Y, beta, L, R) {
    .Call('_NNRPanel_Compute_first_order_poisson_with_LR', PACKAGE = 'NNRPanel', X, Y, beta, L, R)
}

Compute_first_order_poisson_with_LR_FE <- function(X, Y, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_first_order_poisson_with_LR_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, L, R)
}

Compute_second_order_poisson_with_LR <- function(X, beta, L, R) {
    .Call('_NNRPanel_Compute_second_order_poisson_with_LR', PACKAGE = 'NNRPanel', X, beta, L, R)
}

Compute_second_order_poisson_with_LR_FE <- function(X, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_second_order_poisson_with_LR_FE', PACKAGE = 'NNRPanel', X, beta, fe_N, fe_T, L, R)
}

Sim_dynamic_poisson <- function(Z, beta_W, beta_Z, Theta) {
    .Call('_NNRPanel_Sim_dynamic_poisson', PACKAGE = 'NNRPanel', Z, beta_W, beta_Z, Theta)
}

Compute_logl_probit_with_theta <- function(X, Y, beta, Theta) {
    .Call('_NNRPanel_Compute_logl_probit_with_theta', PACKAGE = 'NNRPanel', X, Y, beta, Theta)
}

Compute_logl_probit_with_theta_FE <- function(X, Y, beta, fe_N, fe_T, Theta) {
    .Call('_NNRPanel_Compute_logl_probit_with_theta_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, Theta)
}

Compute_logl_probit_with_LR <- function(X, Y, beta, L, R) {
    .Call('_NNRPanel_Compute_logl_probit_with_LR', PACKAGE = 'NNRPanel', X, Y, beta, L, R)
}

Compute_logl_probit_with_LR_FE <- function(X, Y, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_logl_probit_with_LR_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, L, R)
}

Compute_score_probit_with_theta <- function(X, Y, beta, Theta) {
    .Call('_NNRPanel_Compute_score_probit_with_theta', PACKAGE = 'NNRPanel', X, Y, beta, Theta)
}

Compute_score_probit_with_theta_FE <- function(X, Y, beta, fe_N, fe_T, Theta) {
    .Call('_NNRPanel_Compute_score_probit_with_theta_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, Theta)
}

Compute_score_probit_with_LR <- function(X, Y, beta, L, R) {
    .Call('_NNRPanel_Compute_score_probit_with_LR', PACKAGE = 'NNRPanel', X, Y, beta, L, R)
}

Compute_score_probit_with_LR_FE <- function(X, Y, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_score_probit_with_LR_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, L, R)
}

Compute_obj_probit_with_theta <- function(X, Y, beta, Theta, sigma_sum, phi) {
    .Call('_NNRPanel_Compute_obj_probit_with_theta', PACKAGE = 'NNRPanel', X, Y, beta, Theta, sigma_sum, phi)
}

Compute_obj_probit_with_theta_FE <- function(X, Y, beta, fe_N, fe_T, Theta, sigma_sum, phi) {
    .Call('_NNRPanel_Compute_obj_probit_with_theta_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, Theta, sigma_sum, phi)
}

Compute_obj_probit_with_LR <- function(X, Y, beta, L, R) {
    .Call('_NNRPanel_Compute_obj_probit_with_LR', PACKAGE = 'NNRPanel', X, Y, beta, L, R)
}

Compute_obj_probit_with_LR_FE <- function(X, Y, beta, fe_N, fe_T, L, R) {
    .Call('_NNRPanel_Compute_obj_probit_with_LR_FE', PACKAGE = 'NNRPanel', X, Y, beta, fe_N, fe_T, L, R)
}

Compute_first_order_probit_with_LR <- function(X, Y, beta, L, R) {
    .Call('_NNRPanel_Compute_first_order_probit_with_LR', PACKAGE = 'NNRPanel', X, Y, beta, L, R)
}

Compute_second_order_probit_with_LR <- function(X, Y, beta, L, R) {
    .Call('_NNRPanel_Compute_second_order_probit_with_LR', PACKAGE = 'NNRPanel', X, Y, beta, L, R)
}

